### ISSUE TITLE
Preferred normal direction for adding normals?

### ISSUE THREAD

**Issue by r-chris** [FugroRoames/PointClouds.jl#3]
Would it make sense to flip normals to a preferred direction that we could provide as an optional input parameter to `add_normals` ?

`function pca_normals!(normals, query_points, cloud; neighbours::Int=10, preferred_dir=[0,0,1])`

**Comment by c42f** [comment]
Depends on what you're doing I guess.  For aerial scans this would work most of the time, though not for large buildings with vertical sides.

What you'd be doing with `preferred_dir` is specifying the outward facing `Nref` direction for a glsl-style `faceforward` operation.  In principle `Nref` can be computed per point by flipping the incoming laser ray direction which we should be able to recover from the trajectory and timing information.

So I think it'd be a useful and simple heuristic though we'll be able to do better and different heuristics will apply for indoor-captured data if you had a point cloud but no scanner position.
