### ISSUE TITLE
Register PointClouds in METADATA

### ISSUE THREAD

**Issue by JoshChristie** [FugroRoames/PointClouds.jl#6]
Is it time to register PointClouds.jl?

Is the future of PointClouds heading towards using StaticArrays.jl (which requires 0.5) rather than FixedSizeArrays? If so, can we get this tagged for 0.4 and then work towards moving this over to StaticArrays in 0.5?

**Comment by c42f** [comment]
Makes sense to me, I think StaticArrays is probably the way forward, and tagging before then would probably make sense.

I'm not fully happy with the design at this stage, but that shouldn't prevent us from tagging a version.

**Comment by andyferris** [comment]
Is there a rush to tag? If we're making breaking changes for 0.5, why not
do that first?

**Comment by andyferris** [comment]
I.e. have a publicly tagged version for Julia 0.5 only.

**Comment by c42f** [comment]
I think it's appropriate to tag things which are used in production.  One option is to push the tag to the PointClouds.jl repo, but not register in the public METADATA until the API has settled a bit.

**Comment by JoshChristie** [comment]
Sounds good. I have tagged v0.0.1.
